# Generated by Django 6.0.3 on 2026-03-21 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0002_quizattempt'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='topic',
            field=models.CharField(default='General', max_length=100),
        ),
    ]
