# Generated by Django 6.0.3 on 2026-03-21 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0003_quiz_topic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='topic',
        ),
    ]
