# Generated by Django 6.0.3 on 2026-04-17 18:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_engine', '0002_chatsession_chat_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ai_engine.chatsession'),
        ),
    ]
